# Utiliser une image de base officielle Node.js
FROM node:22

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Créer la structure de dossiers
RUN mkdir -p /app/backend/src
RUN mkdir -p /app/images
RUN mkdir -p /app/shared-images

# Copier les fichiers package.json et package-lock.json
COPY src/package*.json /app/backend/src/

# Se déplacer dans le répertoire backend/src pour installer les dépendances
WORKDIR /app/backend/src

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY src/ /app/backend/src/

# Exposer le port sur lequel l'application va fonctionner
EXPOSE 3000

# Démarrer l'application
CMD ["node", "server.js"]